# Generated by Django 3.1.2 on 2020-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='サブタイトル'),
        ),
    ]
